# Site settings
title: Riccardo Pasianotto
email: riccardo.pasianotto@gmail.com
description: "Actually I'm building stuff with jekyll, stay tuned."
author: "Riccardo Pasianotto"
username: "rkpasia"
baseurl: ""
url: "http://rkpasia.github.io"

# Build settings
markdown: kramdown
permalink: pretty
