# Site settings
title: Riccardo Pasianotto
email: riccardo.pasianotto@gmail.com
description: "Riccardo Pasianotto, web developer based in Italy."
author: "Riccardo Pasianotto"
username: "rkpasia"
baseurl: ""
url: "http://rkpasia.github.io"

# Build settings
markdown: kramdown
permalink: pretty
